---

- name: rust | Install
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

- name: rust | Install toolchain
  shell: "{{ home_dir }}/.cargo/bin/rustup toolchain install {{ rust_version }}"

- name: rust | Install software from the list of cargo items
  shell: "{{ home_dir }}/.cargo/bin/cargo install {{ item.name }}"
  with_items: "{{ cargo_items }}"

- name: rust | Verify cargo items installation
  stat:
    path: "{{ home_dir }}/.cargo/bin/{{ item.binary }}"
  with_items: "{{ cargo_items }}"
  when: item.binary is defined
