---

- name: Clone homeschick
  git:
    repo: https://github.com/andsens/homeshick.git
    dest: "{{ home_dir }}/.homesick/repos/homeshick"

- name: Add setup line for homeshick in .bashrc
  lineinfile:
    path: "{{ home_dir }}/.bashrc"
    regexp: '^source.*homeschick.sh$'
    line: source "$HOME/.homesick/repos/homeshick/homeshick.sh"

- name: Add the homeschick castle from {{ github_dotfiles_path }}
  command: "{{ home_dir }}/.homesick/repos/homeshick/bin/homeshick clone {{ github_dotfiles_path }}"
  args:
    creates: "{{ home_dir }}/.homeschick/repos/dotfiles"
