---

- set_fact:
    homeschick_home: "{{ home_dir }}/.homesick/repos/homeshick"

- name: Clone homeschick
  git:
    repo: https://github.com/andsens/homeshick.git
    dest: "{{ homeschick_home }}"

- name: Clone {{ homeschick_dotfiles }} at branch {{ dotfiles_branch }} into homeschick
  git:
    repo: https://github.com/{{ homeschick_dotfiles }}.git
    dest: "{{ home_dir }}/.homesick/repos/dotfiles"
    version: "{{ dotfiles_branch }}"
    update: no
  when: homeschick_dotfiles is defined

- name: Run homeschick link --force
  command: "{{ homeschick_home }}/bin/homeshick -f link"
