---

- name: Install zsh
  apt:
    name:
    - zsh
    - git
  become: yes
  become_method: sudo

- import_tasks: ohmyzsh.yml
  tags: ohmyzsh

- import_tasks: homeschick.yml
  tags: homeschick

- name: Change the default shell for {{ user }}
  user:
    name: "{{ user }}"
    shell: /bin/zsh
  become: yes
  become_method: sudo
