#!/usr/bin/env ansible-playbook
---

- hosts: localhost
  connection: local
  any_errors_fatal: true
  roles:
    - { role: shell, tags: [shell, common] }
    - { role: common, tags: [common] }
    # - { role: python, tags: python }
    # - { role: apps, tags: apps }
    # - { role: cloud_tools, tags: cloud }
