#!/usr/bin/env ansible-playbook
---

- hosts: localhost
  connection: local
  any_errors_fatal: true
  roles:
    - { role: shell, tags: shell }
    - { role: common, tags: common }
    - { role: hardware, tags: hardware }
    - { role: python, tags: python }
    - { role: node, tags: node }
    - { role: golang, tags: golang }
    - { role: swift, tags: swift }
    - { role: containers, tags: containers }
    - { role: apps, tags: apps }
    - { role: cloud_tools, tags: cloud }
