---

- apt_repository:
    repo: '{{ item }}'
    state: present
  with_items:
    - deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates main restricted
    - deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe
    - deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main restricted
    - deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe
  become: yes
  become_method: sudo

- name: 'Install build dependencies'
  apt:
    name:
    - python3
    - python3-tk
    state: build-dep
  become: yes
  become_method: sudo

- name: 'Install TCL/TK dependencies'
  apt:
    name:
    - libtcl8.6
    - libtk8.6
    - tcl
    - tcl-dev
    - tcl8.6
    - tcl8.6-dev
    - tk
    - tk-dev
    - tk8.6
    - tk8.6-blt2.5
    - tk8.6-dev
    state: present
  become: yes
  become_method: sudo

- name: 'Install other build dependencies'
  apt:
    name:
    - zlib1g-dev
    - libreadline-dev
    - libssl-dev
    - libsqlite3-dev
    - libbz2-dev
    - libgdbm-dev
    - libncurses5-dev
    - xz-utils
    - libxml2-dev
    - libxmlsec1-dev
    - libffi-dev
    - liblzma-dev
    state: present
  become: yes
  become_method: sudo
