---

- name: Install Desktop apps APT packages
  apt:
    name:
    - tilix
    - inkscape
    - gnome-tweaks
    - nautilus-dropbox
    - vlc
    - zeal
    - clementine
    - keepassxc
    - meld
    - gparted
    - virtualbox
    - pandoc
    - network-manager-openvpn
    - chrome-gnome-shell
    - pdf-presenter-console
    state: present

- name: Install energy related packages
  apt:
    name:
    - powernap
    - powertop
    state: present

- name: Install torrent related apps
  apt:
    name:
    - transmission-remote-gtk
    - transmission
    state: present

- name: Install LateX related apps
  apt:
    name:
    - cm-super
    - cm-super-x11
    - lyx
    - texlive-fonts-recommended
    - texlive-science
    - texlive-extra-utils
    state: present

- name: Add Etcher apt repository
  apt_repository:
    repo: deb https://deb.etcher.io stable etcher
    filename: balena-etcher.list
    state: present

- name: Add Etcher apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 379CE192D401AB61

- name: Add Etcher apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 379CE192D401AB61

- name: Install Balena Etcher
  apt:
    name:
    - balena-etcher-electron
    update_cache: yes
    state: present
