---

- name: Add the Docker gpg signing key to Apt
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add the Docker Apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker

- name: Install Docker
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    update_cache: yes
    state: present

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add the user {{ ansible_user }} to the docker group
  user:
    name: "{{ ansible_user }}"
    group: docker
