---
- name: Add Etcher apt repository
  apt_repository:
    repo: deb https://deb.etcher.io stable etcher
    filename: balena-etcher.list
    state: present

- name: Add Etcher apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 379CE192D401AB61

- name: Install Balena Etcher
  apt:
    name:
    - balena-etcher-electron
    update_cache: yes
    state: present
