---

- name: Install snap applications
  snap:
    name:
      - spotify
      - telegram-desktop
      - mailspring
      - insomnia
      - teams-for-linux

- name: Install snap classic applications
  snap:
    name:
      - skype
      - slack
      - pycharm-community
