---



# echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
# curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_$\{VERSION_ID\}/Release.key | sudo apt-key add -
# sudo apt-get update
# sudo apt-get -y upgrade
# sudo apt-get -y install podman


# . /etc/os-release
# sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x${ID^}_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
# wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x${ID^}_${VERSION_ID}/Release.key -O Release.key
# sudo apt-key add - < Release.key
# sudo apt-get update -qq
# sudo apt-get -qq -y install buildah


- name: podman | Add repository apt key
  apt_key:
    keyserver: https://download.opensuse.org
    id: 4d64390375060aa4
    state: present
  become: yes
  become_method: sudo

- name: podman | Add apt repository
  apt_repository:
    repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/ /
    filename: podman
    state: present
  become: yes
  become_method: sudo

- name: podman | Install podman and buildah
  apt:
    name:
    - buildah
    - podman
    update_cache: yes
    state: latest
  become: yes
  become_method: sudo
