---

# CLI
# https://app-updates.agilebits.com/product_history/CLI
# https://cache.agilebits.com/dist/1P/op/pkg/v1.7.0/op_linux_amd64_v1.7.0.zip


- name: Add repository apt key
  apt_key:
    keyring: /usr/share/keyrings/1password.gpg
    keyserver: keyserver.ubuntu.com
    id: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
  become: yes
  become_method: sudo

- name: Add apt repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/1password.gpg] https://downloads.1password.com/linux/debian edge main
    filename: 1password
    state: present
  become: yes
  become_method: sudo

- name: Install
  apt:
    name:
    - 1password
    update_cache: yes
    state: present
  become: yes
  become_method: sudo
