---

- name: desktop | Install Desktop apps APT packages
  apt:
    name:
    - tilix
    - inkscape
    - gnome-tweaks
    - nautilus-dropbox
    - vlc
    - zeal
    - clementine
    - keepassxc
    - meld
    - gparted
    - virtualbox
    - pandoc
    - network-manager-openvpn
    - chrome-gnome-shell
    - pdf-presenter-console
    state: present
  become: yes
  become_method: sudo

- name: desktop | Install energy related packages
  apt:
    name:
    - powernap
    - powertop
    state: present
  become: yes
  become_method: sudo

- name: desktop | Install torrent related apps
  apt:
    name:
    - transmission-remote-gtk
    - transmission
    state: present
  become: yes
  become_method: sudo

- name: desktop | Install LateX related apps
  apt:
    name:
    - cm-super
    - cm-super-x11
    - lyx
    - texlive-fonts-recommended
    - texlive-science
    - texlive-extra-utils
    state: present
  become: yes
  become_method: sudo
