---

- name: Add the Docker gpg signing key to Apt
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes
  become_method: sudo

- name: Add the Docker Apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker
  become: yes
  become_method: sudo

- name: Install Docker
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    update_cache: yes
    state: present
  become: yes
  become_method: sudo

- name: Ensure docker group exists
  group:
    name: docker
    state: present
  become: yes
  become_method: sudo

- name: Add the user {{ user }} to the docker group
  user:
    name: "{{ user }}"
    group: docker
  become: yes
  become_method: sudo

- name: Download dive for docker
  get_url:
    url: https://github.com/wagoodman/dive/releases/download/v0.9.1/dive_0.9.1_linux_amd64.deb
    dest: "{{ home_dir }}/Downloads/dive.deb"
  when: dive_check_deb.rc == 1
  become: yes
  become_method: sudo

- name: Install dive for docker
  apt:
    deb: "{{ home_dir }}/Downloads/dive.deb"
  sudo: true
  when: dive_check_deb.rc == 1
  become: yes
  become_method: sudo

- name: Clone the docker-credential-helpers repository
  git:
    repo: https://github.com/docker/docker-credential-helpers.git
    dest: "{{ home_dir }}/software/docker-credential-helpers"
    version: v.0.6.3

- name: Install build dependencies for docker-credential-helpers
  apt:
    name:
    - libsecrets-1-dev
    state: present
  become: yes
  become_method: sudo

# install 
# link bin/pass in ~/bin
# make pass
# ~/.docker/config.json
# ❯ more ~/.docker/config.json
# {
# 	"auths": {
# 		"https://index.docker.io/v1/": {}
# 	},
# 	"HttpHeaders": {
# 		"User-Agent": "Docker-Client/19.03.2 (linux)"
# 	},
# 	"credsStore": "pass",
# 	"credHelpers": {
# 		"asia.gcr.io": "gcloud",
# 		"eu.gcr.io": "gcloud",
# 		"gcr.io": "gcloud",
# 		"marketplace.gcr.io": "gcloud",
# 		"staging-k8s.gcr.io": "gcloud",
# 		"us.gcr.io": "gcloud"
# 	}
# }
