---

- name: etcher | Add apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 379CE192D401AB61
  become: yes
  become_method: sudo

- name: etcher | Add apt repository
  apt_repository:
    repo: deb https://deb.etcher.io stable etcher
    filename: balena_etcher
    state: present
  become: yes
  become_method: sudo

- name: etcher | Install
  apt:
    name:
    - balena-etcher-electron
    update_cache: yes
    state: present
  become: yes
  become_method: sudo
