
---

- name: github | Add repository apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: C99B11DEB97541F0
  become: yes
  become_method: sudo

- name: github | Add CLI apt repository
  apt_repository:
    repo: deb https://cli.github.com/packages {{ ansible_distribution_release }}
    filename: github
    state: present
  become: yes
  become_method: sudo

- name: github | Install CLI
  apt:
    name:
    - gh
    update_cache: yes
    state: present
  become: yes
  become_method: sudo
