---

- name: snap | Install applications
  snap:
    name:
      - spotify
      - telegram-desktop
      - mailspring
      - insomnia
      - bitwarden
      - bw
      - teams-for-linux
  become: yes
  become_method: sudo

- name: snap | Install classic applications
  snap:
    name:
      - skype
      - slack
      # - pycharm-community
    classic: yes
  become: yes
  become_method: sudo
