---

- name: snap | Install applications
  snap:
    name:
      - spotify
      - telegram-desktop
      - mailspring
      - insomnia
      - bitwarden
      - bw
      - cawbird
      - teams-for-linux
  become: yes
  become_method: sudo

- name: snap | Install classic applications
  snap:
    name:
      - skype
      - slack
      # - pycharm-community
    classic: yes
  become: yes
  become_method: sudo


# ~/bin
# ➜ cat delete_old_snaps.sh
# #!/bin/bash
# # Removes old revisions of snaps
# # CLOSE ALL SNAPS BEFORE RUNNING THIS
# set -eu

# LANG=C snap list --all | awk '/disabled/{print $1, $3}' |
#     while read snapname revision; do
#         snap remove "$snapname" --revision="$revision"
#     done


# sudo snap set system refresh.retain=2
