---

- name: Install snap applications
  snap:
    name:
      - spotify
      - telegram-desktop
      - mailspring
      - insomnia
      - teams-for-linux
  become: yes
  become_method: sudo

- name: Install snap classic applications
  snap:
    name:
      - skype
      - slack
      - pycharm-community
    classic: yes
  become: yes
  become_method: sudo
