---

- name: rust | check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  changed_when: false
  failed_when: false

- name: rust | download installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: yes
  tags:
    - rust

- name: rust | install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust

- name: rust | update rust toolchain
  shell: "{{ home_dir }}/.cargo/bin/rustup update stable"
  tags:
    - rust

- name: rust | install cargo packages
  shell: |
    {{ home_dir }}/.cargo/bin/cargo install '{{ item }}' --locked
  register: cargo_result
  changed_when: "'Installed package' in cargo_result.stderr"
  with_items: "{{ cargo_packages }}"
  tags:
    - rust

- name: rust | install yazi via yazi-build
  shell: |
    {{ home_dir }}/.cargo/bin/cargo install --force yazi-build
  register: yazi_result
  changed_when: "'Installed package' in yazi_result.stderr"
  tags:
    - rust
