---

- name: zed | Check if Zed is installed
  shell: command -v zed
  register: zed_exists
  changed_when: false
  failed_when: false

- name: zed | Install Zed
  when: zed_exists is failed
  shell: curl -fsSL https://zed.dev/install.sh | bash

- name: zed | Install Zed extensions
  shell: "{{ home_dir }}/.local/bin/zed --install-extension {{ item }}"
  failed_when: false
  with_items:
    "{{ zed_extensions }}"
