---

- apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates main restricted
    - deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe
    - deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security main restricted
    - deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security universe
    - deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main restricted
    - deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe
  become: yes
  become_method: sudo

- name: Upgrade APT packages
  apt:
    update_cache: yes
    upgrade: yes
  become: yes
  become_method: sudo

- name: Install APT packages
  apt:
    name:
    - python3
    - python3-dev
    - python3-venv
    - python3-pip
    - xz-utils
    - golang
    - locales
    - tzdata
    - make
    - build-essential
    - llvm
    - curl
    - git
    - ncdu
    - vim
    - gnupg2
    - npm
    - ntp
    - ntpdate
    - ufw
    - sudo
    - apt-transport-https
    - ca-certificates
    - lsb-release
    - software-properties-common
    - ssh
    - exfat-fuse
    - exfat-utils
    - fuse
    - ack
    - jq
    - tig
    - wget
    - ranger
    - direnv
    - tmate
    - neovim
    - fasd
    - graphviz
    - htop
    - bash-completion
    - rsync
    - sshpass
    - pass
    - xdot
    - language-pack-en
    - cmake
    - ttf-mscorefonts-installer
    - apcalc
    - net-tools
    - ssh-askpass-gnome
    - ssh-askpass
    - mtp-tools
    - mtr-tiny
    - yank
    - fzf
    state: present
  become: yes
  become_method: sudo
