---

- name: Install Desktop apps APT packages
  apt:
    name:
    - tilix
    - inkscape
    - gnome-tweaks
    - nautilus-dropbox
    - vlc
    - clementine
    - keepassxc
    - meld
    - virtualbox
    - pandoc
    - network-manager-openvpn
    - chrome-gnome-shell
    - pdf-presenter-console
    state: present

- name: Install energy related packages
  apt:
    name:
    - powernap
    - powertop
    state: present

- name: Install torrent related apps
  apt:
    name:
    - transmission-remote-gtk
    - transmission
    state: present

- name: Install LateX related apps
  apt:
    name:
    - cm-super
    - cm-super-x11
    - lyx
    - texlive-fonts-recommended
    - texlive-science
    - texlive-extra-utils
    state: present

- name: Install NVidia stuff
  apt:
    name:
    - mate-optimus
    state: present

# echo "deb https://deb.etcher.io stable etcher" | sudo tee /etc/apt/sources.list.d/balena-etcher.list
# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61
# balena-etcher-electron
