---

- name: common | Set locale
  locale_gen:
    name: '{{ locale }}'
    state: present
  # command: locale-gen en_GB.UTF-8 && update-locale en_GB.UTF-8

- name: common | Create directories
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'
  loop:
    - '{{ soft_dir }}'
    - '{{ user_local_dir }}'
    - '{{ tmp_install_dir }}'
    - '{{ projects_dir }}'
  become: yes
  become_method: sudo

- include_tasks: apt-tools.yml
  tags: apt
