---

- name:
  pip:
    name:
      - awscli

- set_fact:
    aws_vault_version: 5.3.2
    cw_version: 3.2.3

- name: Download aws-vault
  get_url:
    url: https://github.com/99designs/aws-vault/releases/download/v{{ aws_vault_version }}/aws-vault-linux-amd64
    dest: "{{ bin_dir }}/aws-vault"

- name: Install lucagrulla/cw
  apt:
    deb: https://github.com/lucagrulla/cw/releases/download/v{{ cw_version }}/cw_amd64.deb
  become: yes
  become_method: sudo
