---

- name:
  pip:
    name:
      - awscli

- name: Download aws-vault
  get_url:
    url: https://github.com/99designs/aws-vault/releases/download/v5.0.0-beta3/aws-vault-linux-amd64
    dest: "{{ home_dir }}/bin/"
  when: aws_vault_check.rc == 1

- name: Download cw
  get_url:
    url: https://github.com/lucagrulla/cw/releases/download/v3.2.3/cw_amd64.deb
    dest: /home/{{ ansible_env.USER }}/Downloads/cw.deb
  when: cw_check.rc == 1

- name: Install cw
  apt:
    deb: /home/{{ ansible_env.USER }}/Downloads/cw.deb
  sudo: true
  when: cw_check.rc == 1


