---

- name: Add the Google Cloud gpg signing key to Apt
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add the Google Cloud Apt repository
  apt_repository:
    repo: deb http://packages.cloud.google.com/apt cloud-sdk-{{ ansible_distribution_release }} main
    state: present
    filename: docker

- name: Install Google Cloud SDK
  apt:
    name:
    - google-cloud-sdk
    update_cache: yes
    state: present
