---

- name: packer | Add repository apt key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: yes
  become_method: sudo

- name: packer | Add apt repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    filename: hashicorp_packer
    state: present
  become: yes
  become_method: sudo

- name: packer | Install
  apt:
    name:
    - packer
    update_cache: yes
    state: present
  become: yes
  become_method: sudo
