---

# - set_fact:
#     packer_version: 1.5.4

# - name: Create directory for packer
#   file:
#     path: "{{ home_dir }}/software/packer"
#     state: directory
#     owner: "{{ user }}"
#     group: "{{ group }}"
#   become: yes
#   become_method: sudo

# - name: Unarchive packer {{ packer_version }} package
#   unarchive:
#     src: https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip
#     dest: "{{ home_dir }}/software/packer"
#     remote_src: yes

# - name: Create symbolic link to packer in {{ home_dir }}/bin
#   file:
#     src: "{{ home_dir }}/software/packer/packer"
#     dest: "{{ bin_dir }}/packer"
#     state: link

- name: Add repository apt key
  apt_key:
    keyserver: https://apt.releases.hashicorp.com/gpg
    state: present
  become: yes
  become_method: sudo

- name: Add apt repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    filename: hashicorp_packer
    state: present
  become: yes
  become_method: sudo

- name: Install
  apt:
    name:
    - packer
    update_cache: yes
    state: present
  become: yes
  become_method: sudo
