---

- name: terraform | Clone the tfenv repository in {{ home_dir }}/.tfenv
  git:
    repo: https://github.com/tfutils/tfenv.git
    dest: "{{ home_dir }}/.tfenv"
    update: true

- name: terraform | Add {{ home_dir }}/.tfenv to $PATH
  lineinfile:
    path: "{{ home_dir }}/.bashrc"
    regexp: '^export .*\.tfenv/bin*'
    line: export PATH=$HOME/.tfenv/bin:$PATH
