name: Publish Github Pages

on:
  push:
    branches:
      - master

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: pre-commit/action@v2.0.0

    - uses: ouzi-dev/commit-status-updater@v1.1.0
      with:
        status: "success"

    # - name: Install Python and pipenv
    #   uses: actions/setup-python@v1
    #   with:
    #     python-version: '3.8'

    # - name: Install dependencies
    #   run: make install-ci

    # - name: Run semantic-release
    #   run: poetry run make release
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_BOT_TOKEN }}

    # - name: Commit files
    #   run: |
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git commit -m "[skip ci] new release" -a

    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: Create git tag
      run: make tag
